apiVersion: v1
kind: Service
metadata:
  name: resultapp-service
  labels:
    name: resultapp-pod
    app: resultapp-pod
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30005
  selector:
    name: resultapp-pod
    app: demo-resultapp
