apiVersion: v1
kind: Service
metadata:
  name: votingapp-service
  labels:
    name: votingapp-service
    app: votingapp-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
  selector:
    name: votingapp-pod
    app: demo-votingapp
